# Generated by Django 4.2 on 2024-07-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Статья')),
                ('content', models.TextField(verbose_name='Контент')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-create'],
            },
        ),
    ]
