# Generated by Django 4.2 on 2024-07-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_contract_owner_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_db', to='cabinet.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'База данных',
                'verbose_name_plural': 'Базы данных',
            },
        ),
    ]
